# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-19 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_stock_daily',
            name='volume',
            field=models.IntegerField(blank=True, max_length=11),
        ),
    ]
